### PR TITLE
Modify `jco types` command to accept a configuration file

### PR DESCRIPTION
**Pull request by mjoerussell**
This PR modifies the command `jco types` so that it accepts the same configuration file accepted by `jco transpile`.

We need to use `jco types` to generate Typescript interfaces because this command uses the .wit source files to create types, while `jco transpile` creates types by decoding the compiled WASM code. These binaries don't contain any documentation, so it wasn't available to output to `*.d.ts`.

Without the configuration file, we aren't able to customize the Typescript interface. The key thing that we're missing here is the ability to output Rust enums as Typescript enums.

This PR also includes a quick update to `TsBindgen#type_enum` so that it outputs doc comments for Typescript enum types.

### CODE REVIEW

**Comment by OmarTawfik** [comment]
> The reason is that `jco transpile` generates ts definitions by decoding WASM component binaries, whereas `jco types` parses .wit files directly and uses that information. 

@mjoerussell Thanks for the investigation and the updates!
I wonder if this is an upstream bug, and we should report it to them to fix upstream?
i.e. for `jco transpile` itself to use the  .wit source files to produce TypeScript docs..

**Review by OmarTawfik — COMMENTED** [review]
> The reason is that `jco transpile` generates ts definitions by decoding WASM component binaries, whereas `jco types` parses .wit files directly and uses that information. 

@mjoerussell Thanks for the investigation and the updates!

I wonder if this is an upstream bug, and we should report it to them to fix upstream? i.e. for `jco transpile` itself to use the  .wit source files to produce TypeScript docs. That will keep our fork minimal/benefit the upstream project.

Otherwise, if they are not planning on fixing it, the changes proposed here look great!

**Comment by AntonyBlakey** [comment]
> for `jco transpile` itself to use the .wit source files to produce TypeScript docs

The purpose of `jco transpile` is to take binary components where the `wit source` isn't available, so that isn't a bug.

**Review by AntonyBlakey — APPROVED** [review]

**Comment by OmarTawfik** [comment]
@AntonyBlakey thanks for confirming.

**Pull request merged**
